# Generated by Django 4.2.2 on 2025-04-11 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview_application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('applicant_name', models.CharField(max_length=100)),
                ('applicant_email', models.CharField(max_length=100)),
                ('applicant_phone', models.CharField(max_length=50)),
                ('applicant_address', models.CharField(max_length=500)),
                ('applicant_resume', models.FileField(null=True, upload_to='applicant_resume/')),
                ('applicant_pro_pic', models.ImageField(null=True, upload_to='profile_pictures/')),
                ('applicant_face_matrix', models.TextField(null=True)),
                ('applicant_password', models.CharField(max_length=100, null=True)),
                ('applied_interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.interview_call')),
            ],
        ),
        migrations.CreateModel(
            name='Interview_score',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('score_result', models.IntegerField()),
                ('selected', models.BooleanField(default=False)),
                ('score_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.interview_application', unique=True)),
            ],
        ),
    ]
