# Generated by Django 4.2.2 on 2025-04-11 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_email', models.EmailField(max_length=100)),
                ('admin_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Interview_call',
            fields=[
                ('interview_id', models.AutoField(primary_key=True, serialize=False)),
                ('interview_post', models.CharField(max_length=200)),
                ('interview_min_quali', models.CharField(max_length=200)),
                ('interview_description', models.CharField(max_length=1000)),
                ('interview_pay_scale', models.CharField(max_length=100)),
                ('interview_syllabus', models.CharField(max_length=200)),
                ('interview_date', models.DateTimeField()),
                ('interview_active', models.BooleanField(default=True)),
                ('interview_finished', models.BooleanField(default=False)),
                ('interview_started', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('syllabus_id', models.AutoField(primary_key=True, serialize=False)),
                ('syllabus_name', models.CharField(max_length=200)),
                ('syllabus_file_path', models.FileField(upload_to='syllabus_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Qusetion_answer',
            fields=[
                ('qa_id', models.AutoField(primary_key=True, serialize=False)),
                ('qa_q', models.TextField(unique=True)),
                ('qa_a', models.TextField()),
                ('qa_syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='Interview_syllabus_map',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('map_interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.interview_call')),
                ('map_syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.syllabus')),
            ],
        ),
    ]
